ALTER TABLE T_RECONCILIATION ADD MATCH_LAYER SMALLINT;
ALTER TABLE T_RECONCILIATION ADD MATCH_CONFIDENCE SMALLINT;
ALTER TABLE T_RECONCILIATION ADD MATCH_REASON VARCHAR(80);
ALTER TABLE T_RECONCILIATION ADD MATCHED_AT TIMESTAMP;
