ALTER TABLE T_RECONCILIATION ADD IS_ACTIVE SMALLINT DEFAULT 1;
ALTER TABLE T_RECONCILIATION ADD VOIDED_AT TIMESTAMP;
ALTER TABLE T_RECONCILIATION ADD VOID_REASON VARCHAR(255);
ALTER TABLE T_RECONCILIATION ADD RUN_ID BIGINT;
ALTER TABLE T_RECONCILIATION ADD CREATED_BY VARCHAR(32);
ALTER TABLE T_RECONCILIATION ADD SOURCE_RUN_KIND VARCHAR(16);

ALTER TABLE T_RECONCILIATION_MATCH ADD RUN_ID BIGINT;
ALTER TABLE T_RECONCILIATION_MATCH ADD ERP_SNAPSHOT BLOB SUB_TYPE TEXT;
ALTER TABLE T_RECONCILIATION_MATCH ADD ACQ_SNAPSHOT BLOB SUB_TYPE TEXT;
ALTER TABLE T_RECONCILIATION_MATCH ADD META_JSON BLOB SUB_TYPE TEXT;

CREATE TABLE T_RECON_STATUS (
  INTERDATA_ID BIGINT NOT NULL,
  LAST_RUN_ID BIGINT,
  LAST_ATTEMPT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_REASON VARCHAR(80),
  LAST_DETAILS BLOB SUB_TYPE TEXT,
  ATTEMPTS INTEGER DEFAULT 0,
  CONSTRAINT PK_RECON_STATUS PRIMARY KEY (INTERDATA_ID)
);

CREATE EXCEPTION ex_duplicate_active_recon 'Ja existe conciliacao ativa para este item.';

SET TERM ^;
CREATE OR ALTER TRIGGER TR_RECON_ONLY_ONE_ACTIVE
FOR T_RECONCILIATION
ACTIVE BEFORE INSERT OR UPDATE
AS
BEGIN
  IF (NEW.IS_ACTIVE IS NULL) THEN NEW.IS_ACTIVE = 1;

  IF (NEW.IS_ACTIVE = 1) THEN
  BEGIN
    IF (NEW.INTERDATA_ID IS NOT NULL) THEN
    BEGIN
      IF (EXISTS(
        SELECT 1 FROM T_RECONCILIATION r
        WHERE r.INTERDATA_ID = NEW.INTERDATA_ID
          AND COALESCE(r.IS_ACTIVE,1) = 1
          AND (r.ID <> NEW.ID)
      )) THEN
        EXCEPTION ex_duplicate_active_recon;
    END

    IF (NEW.ACQUIRER IS NOT NULL AND NEW.ACQUIRER_ID IS NOT NULL) THEN
    BEGIN
      IF (EXISTS(
        SELECT 1 FROM T_RECONCILIATION r
        WHERE r.ACQUIRER = NEW.ACQUIRER
          AND r.ACQUIRER_ID = NEW.ACQUIRER_ID
          AND COALESCE(r.IS_ACTIVE,1) = 1
          AND (r.ID <> NEW.ID)
      )) THEN
        EXCEPTION ex_duplicate_active_recon;
    END
  END
END^
SET TERM ;^

CREATE OR ALTER VIEW V_PENDING_INTERDATA AS
SELECT i.*
FROM T_INTERDATA_SALES i
WHERE COALESCE(i.IS_CANCELLED, 0) = 0
  AND NOT EXISTS (
    SELECT 1 FROM T_RECONCILIATION r
    WHERE r.INTERDATA_ID = i.ID
      AND COALESCE(r.IS_ACTIVE, 1) = 1
  );

CREATE OR ALTER VIEW V_PENDING_CIELO AS
SELECT c.*
FROM T_CIELO_SALES c
WHERE NOT EXISTS (
  SELECT 1 FROM T_RECONCILIATION r
  WHERE r.ACQUIRER = 'CIELO'
    AND r.ACQUIRER_ID = c.ID
    AND COALESCE(r.IS_ACTIVE, 1) = 1
  );

CREATE OR ALTER VIEW V_PENDING_SIPAG AS
SELECT c.*
FROM T_SIPAG_SALES c
WHERE NOT EXISTS (
  SELECT 1 FROM T_RECONCILIATION r
  WHERE r.ACQUIRER = 'SIPAG'
    AND r.ACQUIRER_ID = c.ID
    AND COALESCE(r.IS_ACTIVE, 1) = 1
  );

CREATE OR ALTER VIEW V_PENDING_SICREDI AS
SELECT c.*
FROM T_SICREDI_SALES c
WHERE NOT EXISTS (
  SELECT 1 FROM T_RECONCILIATION r
  WHERE r.ACQUIRER = 'SICREDI'
    AND r.ACQUIRER_ID = c.ID
    AND COALESCE(r.IS_ACTIVE, 1) = 1
  );

-- Indices e unique por ROW_HASH devem ser criados manualmente se ja existirem no banco.
-- Sugestoes:
-- CREATE UNIQUE INDEX UX_INTERDATA_ROW_HASH ON T_INTERDATA_SALES (ROW_HASH);
-- CREATE UNIQUE INDEX UX_CIELO_ROW_HASH ON T_CIELO_SALES (ROW_HASH);
-- CREATE UNIQUE INDEX UX_SIPAG_ROW_HASH ON T_SIPAG_SALES (ROW_HASH);
-- CREATE UNIQUE INDEX UX_SICREDI_ROW_HASH ON T_SICREDI_SALES (ROW_HASH);
-- CREATE INDEX IDX_INTERDATA_CANON_CORE ON T_INTERDATA_SALES (CANON_SALE_DATE, CANON_METHOD_GROUP, CANON_GROSS_AMOUNT);
-- CREATE INDEX IDX_CIELO_CANON_CORE ON T_CIELO_SALES (CANON_SALE_DATE, CANON_METHOD_GROUP, CANON_GROSS_AMOUNT);
-- CREATE INDEX IDX_SIPAG_CANON_CORE ON T_SIPAG_SALES (CANON_SALE_DATE, CANON_METHOD_GROUP, CANON_GROSS_AMOUNT);
-- CREATE INDEX IDX_SICREDI_CANON_CORE ON T_SICREDI_SALES (CANON_SALE_DATE, CANON_METHOD_GROUP, CANON_GROSS_AMOUNT);
-- CREATE INDEX IDX_INTERDATA_DATETIME ON T_INTERDATA_SALES (SALE_DATETIME);
-- CREATE INDEX IDX_CIELO_DATETIME ON T_CIELO_SALES (SALE_DATETIME);
-- CREATE INDEX IDX_SIPAG_DATETIME ON T_SIPAG_SALES (SALE_DATETIME);
-- CREATE INDEX IDX_SICREDI_DATETIME ON T_SICREDI_SALES (SALE_DATETIME);
-- CREATE INDEX IDX_CIELO_CANON_TERM ON T_CIELO_SALES (CANON_TERMINAL_NO);
-- CREATE INDEX IDX_SIPAG_CANON_TERM ON T_SIPAG_SALES (CANON_TERMINAL_NO);
-- CREATE INDEX IDX_SICREDI_CANON_TERM ON T_SICREDI_SALES (CANON_TERMINAL_NO);
