SET TERM ^ ;

-- SIPAG EDI domain (payments + UR) - Firebird legacy compatible (idempotente)

-- =========================================================
-- T_SIPAG_PAYMENTS
-- =========================================================
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_SIPAG_PAYMENTS')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE T_SIPAG_PAYMENTS (
        ID BIGINT NOT NULL,
        SOURCE_FILE VARCHAR(255),
        RECORD_TYPE VARCHAR(3),
        ESTABLISHMENT_NO VARCHAR(40),
        SALES_SUMMARY_NO VARCHAR(40),
        SALES_RECEIPT_NO VARCHAR(80),
        AUTH_CODE VARCHAR(40),
        ID_UR VARCHAR(80),
        PAYMENT_DATE DATE,
        SALE_DATETIME TIMESTAMP,
        BRAND VARCHAR(80),
        PAYMENT_METHOD VARCHAR(120),
        PAYMENT_STATUS VARCHAR(120),
        GROSS_AMOUNT NUMERIC(18,2),
        FEE_AMOUNT NUMERIC(18,2),
        NET_AMOUNT NUMERIC(18,2),
        PLAN_TOTAL NUMERIC(18,2),
        ROW_HASH VARCHAR(64),
        RAW_LINE BLOB SUB_TYPE TEXT,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_T_SIPAG_PAYMENTS PRIMARY KEY (ID)
      )';
  END
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_SIPAG_PAYMENTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_SIPAG_PAYMENTS_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_SIPAG_PAYMENTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_SIPAG_PAYMENTS_ID FOR T_SIPAG_PAYMENTS ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_T_SIPAG_PAYMENTS_ID, 1); END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'UX_SIPAG_PAYMENTS_ROW_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_SIPAG_PAYMENTS_ROW_HASH ON T_SIPAG_PAYMENTS (ROW_HASH)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_PAYMENTS_DATE')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_PAYMENTS_DATE ON T_SIPAG_PAYMENTS (PAYMENT_DATE)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_PAYMENTS_UR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_PAYMENTS_UR ON T_SIPAG_PAYMENTS (ID_UR)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_PAYMENTS_NSU')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_PAYMENTS_NSU ON T_SIPAG_PAYMENTS (SALES_RECEIPT_NO)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_PAYMENTS_AUTH')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_PAYMENTS_AUTH ON T_SIPAG_PAYMENTS (AUTH_CODE)';
END^

-- =========================================================
-- T_SIPAG_UR
-- =========================================================
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_SIPAG_UR')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE T_SIPAG_UR (
        ID BIGINT NOT NULL,
        ID_UR VARCHAR(80) NOT NULL,
        SOURCE_FILE VARCHAR(255),
        REF_DATE DATE,
        BRAND VARCHAR(80),
        PRODUCT VARCHAR(120),
        CONSTITUTED_AMOUNT NUMERIC(18,2),
        AVAILABLE_AMOUNT NUMERIC(18,2),
        PAID_AMOUNT NUMERIC(18,2),
        OPEN_AMOUNT NUMERIC(18,2),
        STATUS VARCHAR(120),
        ROW_HASH VARCHAR(64),
        RAW_LINE BLOB SUB_TYPE TEXT,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_T_SIPAG_UR PRIMARY KEY (ID)
      )';
  END
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_SIPAG_UR_ID')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_SIPAG_UR_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_SIPAG_UR_ID')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_SIPAG_UR_ID FOR T_SIPAG_UR ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_T_SIPAG_UR_ID, 1); END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'UX_SIPAG_UR_ID_UR')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_SIPAG_UR_ID_UR ON T_SIPAG_UR (ID_UR)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_UR_REF_DATE')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_UR_REF_DATE ON T_SIPAG_UR (REF_DATE)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_UR_ROW_HASH')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_UR_ROW_HASH ON T_SIPAG_UR (ROW_HASH)';
END^

-- =========================================================
-- T_SIPAG_UR_CONTRACTS
-- =========================================================
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_SIPAG_UR_CONTRACTS')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE T_SIPAG_UR_CONTRACTS (
        ID BIGINT NOT NULL,
        ID_UR VARCHAR(80) NOT NULL,
        CONTRACT_ID VARCHAR(80),
        REF_DATE DATE,
        AMOUNT NUMERIC(18,2),
        ROW_HASH VARCHAR(64),
        RAW_LINE BLOB SUB_TYPE TEXT,
        SOURCE_FILE VARCHAR(255),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_T_SIPAG_UR_CONTRACTS PRIMARY KEY (ID)
      )';
  END
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_SIPAG_UR_CONTRACTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_SIPAG_UR_CONTRACTS_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_SIPAG_UR_CONTRACTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_SIPAG_UR_CONTRACTS_ID FOR T_SIPAG_UR_CONTRACTS ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_T_SIPAG_UR_CONTRACTS_ID, 1); END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'UX_SIPAG_UR_CONTRACTS_ROW_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_SIPAG_UR_CONTRACTS_ROW_HASH ON T_SIPAG_UR_CONTRACTS (ROW_HASH)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_UR_CONTRACTS_UR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_UR_CONTRACTS_UR ON T_SIPAG_UR_CONTRACTS (ID_UR)';
END^

-- =========================================================
-- T_SIPAG_UR_DEDUCTIONS
-- =========================================================
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_SIPAG_UR_DEDUCTIONS')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE T_SIPAG_UR_DEDUCTIONS (
        ID BIGINT NOT NULL,
        ID_UR VARCHAR(80) NOT NULL,
        DEDUCTION_TYPE VARCHAR(120),
        REF_DATE DATE,
        AMOUNT NUMERIC(18,2),
        ROW_HASH VARCHAR(64),
        RAW_LINE BLOB SUB_TYPE TEXT,
        SOURCE_FILE VARCHAR(255),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_T_SIPAG_UR_DEDUCTIONS PRIMARY KEY (ID)
      )';
  END
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_SIPAG_UR_DEDUCTIONS_ID')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_SIPAG_UR_DEDUCTIONS_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_SIPAG_UR_DEDUCTIONS_ID')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_SIPAG_UR_DEDUCTIONS_ID FOR T_SIPAG_UR_DEDUCTIONS ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_T_SIPAG_UR_DEDUCTIONS_ID, 1); END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'UX_SIPAG_UR_DEDUCTIONS_ROW_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_SIPAG_UR_DEDUCTIONS_ROW_HASH ON T_SIPAG_UR_DEDUCTIONS (ROW_HASH)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_UR_DEDUCTIONS_UR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_UR_DEDUCTIONS_UR ON T_SIPAG_UR_DEDUCTIONS (ID_UR)';
END^

-- =========================================================
-- T_SIPAG_UR_PAYMENTS
-- =========================================================
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_SIPAG_UR_PAYMENTS')) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE T_SIPAG_UR_PAYMENTS (
        ID BIGINT NOT NULL,
        ID_UR VARCHAR(80) NOT NULL,
        PAYMENT_ID VARCHAR(80),
        PAYMENT_DATE DATE,
        AMOUNT NUMERIC(18,2),
        STATUS VARCHAR(120),
        ROW_HASH VARCHAR(64),
        RAW_LINE BLOB SUB_TYPE TEXT,
        SOURCE_FILE VARCHAR(255),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_T_SIPAG_UR_PAYMENTS PRIMARY KEY (ID)
      )';
  END
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_SIPAG_UR_PAYMENTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_SIPAG_UR_PAYMENTS_ID';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_SIPAG_UR_PAYMENTS_ID')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_SIPAG_UR_PAYMENTS_ID FOR T_SIPAG_UR_PAYMENTS ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_T_SIPAG_UR_PAYMENTS_ID, 1); END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'UX_SIPAG_UR_PAYMENTS_ROW_HASH')) THEN
    EXECUTE STATEMENT 'CREATE UNIQUE INDEX UX_SIPAG_UR_PAYMENTS_ROW_HASH ON T_SIPAG_UR_PAYMENTS (ROW_HASH)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_SIPAG_UR_PAYMENTS_UR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SIPAG_UR_PAYMENTS_UR ON T_SIPAG_UR_PAYMENTS (ID_UR)';
END^

SET TERM ; ^
