SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'EDI_SOURCE_KIND'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD EDI_SOURCE_KIND VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'MATRIX_CLIENT_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD MATRIX_CLIENT_CODE VARCHAR(20)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'SALES_SUMMARY_NUMBER'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD SALES_SUMMARY_NUMBER VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_TYPE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_TYPE_DESC VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_STATUS_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_STATUS_CODE VARCHAR(16)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_STATUS_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_STATUS_DESC VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CARD_SCHEME_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CARD_SCHEME_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CARD_SCHEME_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CARD_SCHEME_DESC VARCHAR(40)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CARD_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CARD_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'ENTRY_MODE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD ENTRY_MODE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'ENTRY_MODE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD ENTRY_MODE_DESC VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TECHNOLOGY_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TECHNOLOGY_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TECHNOLOGY_TYPE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TECHNOLOGY_TYPE_DESC VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_ACCOUNT_REFERENCE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_ACCOUNT_REFERENCE VARCHAR(64)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'ID_UR'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD ID_UR VARCHAR(64)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'FEE_PERCENT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD FEE_PERCENT NUMERIC(9,4)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'INTERCHANGE_PLUS_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD INTERCHANGE_PLUS_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'INTERCHANGE_FEE_PERCENT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD INTERCHANGE_FEE_PERCENT NUMERIC(9,4)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CASHBACK_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CASHBACK_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'REVERSE_INTERCHANGE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD REVERSE_INTERCHANGE NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_INSTRUCTION_NO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_INSTRUCTION_NO VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'FINANCE_SUMMARY_NUMBER'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD FINANCE_SUMMARY_NUMBER VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'SALES_REFERENCE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD SALES_REFERENCE VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'VALUE_DATE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD VALUE_DATE DATE';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_DATE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_DATE DATE';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_TIME'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_TIME VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_TYPE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_TYPE_DESC VARCHAR(40)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_TRANSACTION_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_TRANSACTION_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'PAYMENT_TRANSACTION_TYPE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD PAYMENT_TRANSACTION_TYPE_DESC VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'RECEIPT_TYPE_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD RECEIPT_TYPE_CODE VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'RECEIPT_TYPE_DESC'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD RECEIPT_TYPE_DESC VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_DESCRIPTION_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_DESCRIPTION_CODE VARCHAR(16)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'TRANSACTION_DESCRIPTION'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD TRANSACTION_DESCRIPTION VARCHAR(80)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'FEE_MODE_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD FEE_MODE_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'FEE_MODE_NET_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD FEE_MODE_NET_AMOUNT NUMERIC(15,2)';
END^

SET TERM ; ^
