ALTER TABLE T_RECONCILIATION_MATCH ADD MATCH_LAYER INTEGER;
ALTER TABLE T_RECONCILIATION_MATCH ADD MATCH_CONFIDENCE SMALLINT;
ALTER TABLE T_RECONCILIATION_MATCH ADD MATCH_REASON VARCHAR(200);

CREATE INDEX IX_RECON_MATCH_LAYER ON T_RECONCILIATION_MATCH (MATCH_LAYER);
