SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_FEE_AMOUNT'
  )) THEN
    EXECUTE STATEMENT '
      UPDATE T_SIPAG_SALES
         SET CANON_FEE_AMOUNT = FEE_AMOUNT
       WHERE CANON_FEE_AMOUNT IS NULL
         AND FEE_AMOUNT IS NOT NULL';
END^

EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_NET_AMOUNT'
  )) THEN
    EXECUTE STATEMENT '
      UPDATE T_SIPAG_SALES
         SET CANON_NET_AMOUNT = NET_AMOUNT
       WHERE CANON_NET_AMOUNT IS NULL
         AND NET_AMOUNT IS NOT NULL';
END^

EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_PERC_TAXA'
  )) THEN
    EXECUTE STATEMENT '
      UPDATE T_SIPAG_SALES
         SET CANON_PERC_TAXA = CAST((FEE_AMOUNT / GROSS_AMOUNT) * 100 AS NUMERIC(9,4))
       WHERE CANON_PERC_TAXA IS NULL
         AND FEE_AMOUNT IS NOT NULL
         AND GROSS_AMOUNT IS NOT NULL
         AND GROSS_AMOUNT <> 0';
END^

SET TERM ; ^
