SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_SALE_DATE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_SALE_DATE DATE';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_METHOD'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_METHOD VARCHAR(16)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_METHOD_GROUP'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_METHOD_GROUP VARCHAR(8)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_BRAND'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_BRAND VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_TERMINAL_NO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_TERMINAL_NO VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_AUTH_CODE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_AUTH_CODE VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_NSU'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_NSU VARCHAR(32)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_GROSS_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_GROSS_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_FEE_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_FEE_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_NET_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_NET_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_PERC_TAXA'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_PERC_TAXA NUMERIC(9,4)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_INSTALLMENT_NO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_INSTALLMENT_NO SMALLINT';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SICREDI_SALES' AND RDB$FIELD_NAME = 'CANON_INSTALLMENT_TOTAL'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SICREDI_SALES ADD CANON_INSTALLMENT_TOTAL SMALLINT';
END^

EXECUTE BLOCK AS
BEGIN
  EXECUTE STATEMENT '
    UPDATE T_SICREDI_SALES
       SET CANON_SALE_DATE = COALESCE(CANON_SALE_DATE, CAST(SALE_DATETIME AS DATE)),
           CANON_METHOD = COALESCE(
             CANON_METHOD,
             CASE
               WHEN UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%PIX%'' THEN ''PIX''
               WHEN UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%VOUCHER%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%ALELO%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%TICKET%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%SODEXO%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''% VR %''
               THEN ''VOUCHER''
               WHEN UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%DEBIT%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%DEBITO%''
               THEN ''DEBITO''
               WHEN UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%CRED%''
                 OR UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%CREDITO%''
               THEN ''CREDITO''
               ELSE ''CARD''
             END
           ),
           CANON_METHOD_GROUP = COALESCE(
             CANON_METHOD_GROUP,
             CASE
               WHEN UPPER(COALESCE(CANON_METHOD, '''')) LIKE ''%PIX%'' THEN ''PIX''
               WHEN UPPER(COALESCE(PRODUCT, '''') || '' '' || COALESCE(CARD_TYPE, '''') || '' '' || COALESCE(BRAND, '''')) LIKE ''%PIX%'' THEN ''PIX''
               ELSE ''CARD''
             END
           ),
           CANON_BRAND = COALESCE(CANON_BRAND, SUBSTRING(COALESCE(BRAND, '''') FROM 1 FOR 32)),
           CANON_TERMINAL_NO = COALESCE(CANON_TERMINAL_NO, SUBSTRING(COALESCE(TERMINAL_NO, '''') FROM 1 FOR 32)),
           CANON_AUTH_CODE = COALESCE(CANON_AUTH_CODE, SUBSTRING(COALESCE(AUTH_CODE, '''') FROM 1 FOR 32)),
           CANON_NSU = COALESCE(CANON_NSU, SUBSTRING(COALESCE(SALE_RECEIPT, PAYMENT_CODE, CARD_REF_CODE, '''') FROM 1 FOR 32)),
           CANON_GROSS_AMOUNT = COALESCE(CANON_GROSS_AMOUNT, GROSS_AMOUNT),
           CANON_FEE_AMOUNT = COALESCE(CANON_FEE_AMOUNT, MDR_AMOUNT),
           CANON_NET_AMOUNT = COALESCE(CANON_NET_AMOUNT, NET_AMOUNT),
           CANON_PERC_TAXA = COALESCE(CANON_PERC_TAXA, CASE WHEN GROSS_AMOUNT IS NOT NULL AND GROSS_AMOUNT <> 0 AND MDR_AMOUNT IS NOT NULL THEN CAST((MDR_AMOUNT / GROSS_AMOUNT) * 100 AS NUMERIC(9,4)) ELSE NULL END),
           CANON_INSTALLMENT_NO = COALESCE(CANON_INSTALLMENT_NO, 1),
           CANON_INSTALLMENT_TOTAL = COALESCE(CANON_INSTALLMENT_TOTAL, 1)
  ';
END^

SET TERM ; ^
