SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_FEE_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SIPAG_SALES ADD CANON_FEE_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_NET_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SIPAG_SALES ADD CANON_NET_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SIPAG_SALES'
      AND RDB$FIELD_NAME = 'CANON_PERC_TAXA'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_SIPAG_SALES ADD CANON_PERC_TAXA NUMERIC(9,4)';
END^

SET TERM ; ^
