SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_RECONCILIATION'
      AND RDB$FIELD_NAME = 'ACQ_FEE_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_RECONCILIATION ADD ACQ_FEE_AMOUNT NUMERIC(15,2)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_RECONCILIATION'
      AND RDB$FIELD_NAME = 'ACQ_PERC_TAXA'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_RECONCILIATION ADD ACQ_PERC_TAXA NUMERIC(9,4)';
END^

SET TERM ; ^
