SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES')) THEN
    EXECUTE STATEMENT 'CREATE TABLE T_EDI_CIELO_AJUSTES (
      ID BIGINT,
      ADJUSTMENT_DATETIME TIMESTAMP,
      ESTABLISHMENT_NO VARCHAR(30),
      PAYMENT_METHOD VARCHAR(30),
      BRAND VARCHAR(30),
      NSU_DOC VARCHAR(40),
      AUTH_CODE VARCHAR(20),
      ENTRY_TYPE VARCHAR(255),
      REASON VARCHAR(255),
      GROSS_AMOUNT NUMERIC(15,2),
      FEE_AMOUNT NUMERIC(15,2),
      NET_AMOUNT NUMERIC(15,2),
      SETTLEMENT_DATE DATE,
      FILE_SHA256 VARCHAR(64),
      ROW_HASH CHAR(64),
      CREATED_AT TIMESTAMP
    )';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'FILE_NAME')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD FILE_NAME VARCHAR(255)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'FILE_SEQ')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD FILE_SEQ INTEGER';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'FILE_DATE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD FILE_DATE DATE';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'LINE_NO')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD LINE_NO INTEGER';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'EC')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD EC VARCHAR(10)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_TYPE_CODE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_TYPE_CODE VARCHAR(5)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_REASON_CODE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_REASON_CODE VARCHAR(5)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_GROSS_SIGN')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_GROSS_SIGN CHAR(1)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_GROSS')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_GROSS NUMERIC(15,2)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_FEE_SIGN')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_FEE_SIGN CHAR(1)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_FEE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_FEE NUMERIC(15,2)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_NET_SIGN')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_NET_SIGN CHAR(1)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'ADJ_NET')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD ADJ_NET NUMERIC(15,2)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'REFERENCE_DATE')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD REFERENCE_DATE DATE';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'UR_KEY')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD UR_KEY VARCHAR(120)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'NSU_ORIGINAL')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD NSU_ORIGINAL VARCHAR(20)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES' AND RDB$FIELD_NAME = 'BLOCK_HASH')) THEN
    EXECUTE STATEMENT 'ALTER TABLE T_EDI_CIELO_AJUSTES ADD BLOCK_HASH CHAR(64)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T_EDI_CIELO_AJUSTES_ITENS')) THEN
    EXECUTE STATEMENT 'CREATE TABLE T_EDI_CIELO_AJUSTES_ITENS (
      ID BIGINT,
      AJUSTE_ID BIGINT NOT NULL,
      SALE_ID BIGINT,
      FILE_NAME VARCHAR(255),
      LINE_NO INTEGER,
      EC VARCHAR(10),
      NSU_CIELO VARCHAR(20),
      AUTH_CODE VARCHAR(10),
      SALE_DATE DATE,
      SALE_TIME TIME,
      BRAND_CODE VARCHAR(5),
      PRODUCT_CODE VARCHAR(5),
      CARD_BIN VARCHAR(6),
      CARD_LAST4 VARCHAR(4),
      UR_KEY VARCHAR(120),
      GROSS NUMERIC(15,2),
      NET NUMERIC(15,2),
      FEE NUMERIC(15,2),
      RAW_LINE BLOB SUB_TYPE TEXT,
      ROW_HASH CHAR(64)
    )';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME = 'GEN_T_EDI_CIELO_AJUSTES_ITENS')) THEN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_T_EDI_CIELO_AJUSTES_ITENS';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'BI_T_EDI_CIELO_AJUSTES_ITENS')) THEN
    EXECUTE STATEMENT 'CREATE TRIGGER BI_T_EDI_CIELO_AJUSTES_ITENS FOR T_EDI_CIELO_AJUSTES_ITENS ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_T_EDI_CIELO_AJUSTES_ITENS, 1);
END';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_CIELO_AJ_ITENS_FILE_LINE')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_CIELO_AJ_ITENS_FILE_LINE ON T_EDI_CIELO_AJUSTES_ITENS (FILE_NAME, LINE_NO)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_CIELO_AJ_ITENS_EC_NSU')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_CIELO_AJ_ITENS_EC_NSU ON T_EDI_CIELO_AJUSTES_ITENS (EC, NSU_CIELO)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_CIELO_AJ_ITENS_EC_AUTH')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_CIELO_AJ_ITENS_EC_AUTH ON T_EDI_CIELO_AJUSTES_ITENS (EC, AUTH_CODE, SALE_DATE)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_CIELO_AJ_ITENS_EC_UR')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_CIELO_AJ_ITENS_EC_UR ON T_EDI_CIELO_AJUSTES_ITENS (EC, UR_KEY)';
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_CIELO_AJ_ITENS_SALE')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_CIELO_AJ_ITENS_SALE ON T_EDI_CIELO_AJUSTES_ITENS (SALE_ID)';
END^

SET TERM ; ^
