CREATE TABLE T_EDI_CIELO_AJUSTES (
  ID BIGINT NOT NULL,
  ADJUSTMENT_DATETIME TIMESTAMP,
  ESTABLISHMENT_NO VARCHAR(30),
  PAYMENT_METHOD VARCHAR(60),
  BRAND VARCHAR(50),
  NSU_DOC VARCHAR(50),
  AUTH_CODE VARCHAR(50),
  ENTRY_TYPE VARCHAR(60),
  REASON VARCHAR(120),
  GROSS_AMOUNT NUMERIC(15,2),
  FEE_AMOUNT NUMERIC(15,2),
  NET_AMOUNT NUMERIC(15,2),
  SETTLEMENT_DATE TIMESTAMP,
  FILE_SHA256 VARCHAR(64),
  ROW_HASH VARCHAR(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_T_EDI_CIELO_AJUSTES PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_T_EDI_CIELO_AJUSTES;

SET TERM ^ ;
CREATE OR ALTER TRIGGER BI_T_EDI_CIELO_AJUSTES FOR T_EDI_CIELO_AJUSTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_T_EDI_CIELO_AJUSTES;
END^
SET TERM ; ^

CREATE UNIQUE INDEX UX_T_EDI_CIELO_AJUSTES_ROWHASH ON T_EDI_CIELO_AJUSTES (ROW_HASH);
