CREATE INDEX IX_INTERDATA_SALE_DATETIME ON T_INTERDATA_SALES (SALE_DATETIME);
CREATE INDEX IX_INTERDATA_GROSS_AMOUNT ON T_INTERDATA_SALES (GROSS_AMOUNT);
CREATE INDEX IX_INTERDATA_NSU ON T_INTERDATA_SALES (NSU);
CREATE INDEX IX_INTERDATA_AUTH_NSU ON T_INTERDATA_SALES (AUTH_NSU);
CREATE INDEX IX_INTERDATA_AUTH_CODE ON T_INTERDATA_SALES (AUTH_CODE);
CREATE INDEX IX_INTERDATA_TID ON T_INTERDATA_SALES (TID);

CREATE INDEX IX_CIELO_SALE_DATETIME ON T_CIELO_SALES (SALE_DATETIME);
CREATE INDEX IX_CIELO_GROSS_AMOUNT ON T_CIELO_SALES (GROSS_AMOUNT);
CREATE INDEX IX_CIELO_NSU_DOC ON T_CIELO_SALES (NSU_DOC);
CREATE INDEX IX_CIELO_AUTH_CODE ON T_CIELO_SALES (AUTH_CODE);
CREATE INDEX IX_CIELO_TID ON T_CIELO_SALES (TID);

CREATE INDEX IX_SIPAG_SALE_DATETIME ON T_SIPAG_SALES (SALE_DATETIME);
CREATE INDEX IX_SIPAG_GROSS_AMOUNT ON T_SIPAG_SALES (GROSS_AMOUNT);
CREATE INDEX IX_SIPAG_TRANSACTION_NO ON T_SIPAG_SALES (TRANSACTION_NO);
CREATE INDEX IX_SIPAG_AUTH_NO ON T_SIPAG_SALES (AUTH_NO);
CREATE INDEX IX_SIPAG_SALE_ID ON T_SIPAG_SALES (SALE_ID);
