CREATE SEQUENCE GEN_RECONCILIATION_ID;

CREATE TABLE T_RECONCILIATION (
  ID BIGINT NOT NULL,
  INTERDATA_ID BIGINT,
  ACQUIRER_ID BIGINT,
  ACQUIRER VARCHAR(20),
  SALE_NO VARCHAR(60),
  AUTH_NSU VARCHAR(60),
  ACQ_AUTH_CODE VARCHAR(60),
  ACQ_NSU VARCHAR(60),
  SALE_DATETIME TIMESTAMP,
  ACQ_SALE_DATETIME TIMESTAMP,
  GROSS_AMOUNT NUMERIC(15, 2),
  ACQ_GROSS_AMOUNT NUMERIC(15, 2),
  NET_AMOUNT NUMERIC(15, 2),
  ACQ_NET_AMOUNT NUMERIC(15, 2),
  STATUS VARCHAR(60),
  MATCH_TYPE VARCHAR(30),
  MATCH_SCORE INTEGER,
  AMOUNT_DIFF NUMERIC(15, 2),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_RECONCILIATION PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UX_RECONCILIATION_INTERDATA ON T_RECONCILIATION (INTERDATA_ID);
CREATE UNIQUE INDEX UX_RECONCILIATION_ACQ ON T_RECONCILIATION (ACQUIRER, ACQUIRER_ID);
CREATE INDEX IX_RECONCILIATION_SALE_DATETIME ON T_RECONCILIATION (SALE_DATETIME);

SET TERM ^ ;
CREATE OR ALTER TRIGGER BI_RECONCILIATION FOR T_RECONCILIATION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_RECONCILIATION_ID;
END^
SET TERM ; ^
