CREATE SEQUENCE GEN_CIELO_SALES_ID;
CREATE SEQUENCE GEN_SIPAG_SALES_ID;
CREATE SEQUENCE GEN_SICREDI_SALES_ID;

CREATE TABLE T_CIELO_SALES (
  ID BIGINT NOT NULL,
  SALE_DATETIME TIMESTAMP,
  ESTABLISHMENT_NO VARCHAR(30),
  PAYMENT_METHOD VARCHAR(60),
  BRAND VARCHAR(50),
  GROSS_AMOUNT NUMERIC(15, 2),
  FEE_AMOUNT NUMERIC(15, 2),
  NET_AMOUNT NUMERIC(15, 2),
  STATUS VARCHAR(60),
  ENTRY_TYPE VARCHAR(60),
  REASON VARCHAR(120),
  ENTRY_DATE TIMESTAMP,
  SETTLEMENT_DATE TIMESTAMP,
  AUTH_CODE VARCHAR(50),
  NSU_DOC VARCHAR(50),
  SALE_CODE VARCHAR(80),
  TID VARCHAR(80),
  CARD_ORIGIN VARCHAR(60),
  PIX_ID VARCHAR(80),
  TX_ID VARCHAR(80),
  PIX_PAYMENT_ID VARCHAR(80),
  CARD_NUMBER VARCHAR(30),
  ORDER_NUMBER VARCHAR(60),
  INVOICE_NUMBER VARCHAR(60),
  BATCH_NUMBER VARCHAR(60),
  SALES_CHANNEL VARCHAR(60),
  MODALITY VARCHAR(60),
  CAPTURE_TYPE VARCHAR(60),
  MACHINE_NUMBER VARCHAR(40),
  TOTAL_FEES NUMERIC(9, 2),
  MDR_RATE NUMERIC(9, 2),
  TERM_RATE NUMERIC(9, 2),
  MDR_AMOUNT NUMERIC(15, 2),
  TERM_AMOUNT NUMERIC(15, 2),
  CASH_AMOUNT NUMERIC(15, 2),
  CHANGE_AMOUNT NUMERIC(15, 2),
  ORIGIN_VALUE VARCHAR(120),
  ORIGIN_DOCUMENT VARCHAR(60),
  ORIGIN_INSTITUTION VARCHAR(120),
  DEST_VALUE VARCHAR(120),
  DEST_DOCUMENT VARCHAR(60),
  DEST_INSTITUTION VARCHAR(120),
  ROW_HASH VARCHAR(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_CIELO_SALES PRIMARY KEY (ID)
);

CREATE TABLE T_SIPAG_SALES (
  ID BIGINT NOT NULL,
  ESTABLISHMENT_NO VARCHAR(30),
  SALE_DATETIME TIMESTAMP,
  TRANSACTION_NO VARCHAR(50),
  SALE_ID VARCHAR(80),
  BRAND VARCHAR(50),
  PAYMENT_METHOD VARCHAR(60),
  PLAN_DESC VARCHAR(50),
  INSTALLMENT_NO INTEGER,
  INSTALLMENT_TOTAL INTEGER,
  AUTH_NO VARCHAR(50),
  CARD_TYPE VARCHAR(50),
  CARD_NUMBER VARCHAR(50),
  TERMINAL_NO VARCHAR(50),
  CAPTURE_TYPE VARCHAR(50),
  CREDIT_DEBIT_IND VARCHAR(10),
  CANCEL_IND VARCHAR(10),
  SUMMARY_NO VARCHAR(50),
  SETTLEMENT_DATE TIMESTAMP,
  YOUR_NUMBER VARCHAR(50),
  PAYMENT_ORDER_NO VARCHAR(50),
  STATUS VARCHAR(80),
  GROSS_AMOUNT NUMERIC(15, 2),
  FEE_AMOUNT NUMERIC(15, 2),
  NET_AMOUNT NUMERIC(15, 2),
  PLAN_TOTAL NUMERIC(15, 2),
  ROW_HASH VARCHAR(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_SIPAG_SALES PRIMARY KEY (ID)
);

CREATE TABLE T_SICREDI_SALES (
  ID BIGINT NOT NULL,
  SALE_DATETIME TIMESTAMP,
  AUTH_CODE VARCHAR(50),
  ESTABLISHMENT_CODE VARCHAR(30),
  ESTABLISHMENT_NAME VARCHAR(120),
  SALE_RECEIPT VARCHAR(60),
  ORDER_NO VARCHAR(60),
  SALES_CHANNEL VARCHAR(60),
  TERMINAL_NO VARCHAR(60),
  PRODUCT VARCHAR(60),
  CARD_TYPE VARCHAR(60),
  BRAND VARCHAR(60),
  STATUS VARCHAR(60),
  GROSS_AMOUNT NUMERIC(15, 2),
  MDR_AMOUNT NUMERIC(15, 2),
  NET_AMOUNT NUMERIC(15, 2),
  ORDER_ID_DESC VARCHAR(80),
  CARD_NUMBER VARCHAR(50),
  PREPAID VARCHAR(30),
  EXPECTED_PAY_DATE TIMESTAMP,
  PAY_STATUS VARCHAR(80),
  PAY_DATE TIMESTAMP,
  PAYMENT_CODE VARCHAR(60),
  CARD_REF_CODE VARCHAR(60),
  CARD_ORIGIN VARCHAR(60),
  ROW_HASH VARCHAR(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_SICREDI_SALES PRIMARY KEY (ID)
);

SET TERM ^ ;
CREATE OR ALTER TRIGGER BI_CIELO_SALES FOR T_CIELO_SALES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_CIELO_SALES_ID;
END^
CREATE OR ALTER TRIGGER BI_SIPAG_SALES FOR T_SIPAG_SALES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_SIPAG_SALES_ID;
END^
CREATE OR ALTER TRIGGER BI_SICREDI_SALES FOR T_SICREDI_SALES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_SICREDI_SALES_ID;
END^
SET TERM ; ^
